-- 1. Table: Profil
CREATE TABLE Profil (
    ID_profil INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_P VARCHAR(100),
    description_p VARCHAR(255)
);

-- 2. Table: Utilisateur
CREATE TABLE Utilisateur (
    ID_User INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Login VARCHAR(100),
    Password VARCHAR(100),
    Profil_ID INT,
    Mbre_ID INT,
    FOREIGN KEY (Profil_ID) REFERENCES Profil(ID_profil)
    -- Note: Relationship to Membre depends on business logic,
    -- often added later via ALTER TABLE or handled via application logic.
);

-- 3. Table: Categorie
CREATE TABLE Categorie (
    ID_cat INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nom_cat VARCHAR(100),
    Champ VARCHAR(100)
);

-- 4. Table: Auteur
CREATE TABLE Auteur (
    ID_auteur INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nom_auteur VARCHAR(100),
    Prenom_auteur VARCHAR(100)
);

-- 5. Table: Livre
CREATE TABLE Livre (
    ID_Livre INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ISBN VARCHAR(20),
    Titre VARCHAR(255),
    Quantite INT,
    Cat_ID INT,
    FOREIGN KEY (Cat_ID) REFERENCES Categorie(ID_cat)
);

-- 6. Table: Livre_Auteur (Associative table for Many-to-Many)
CREATE TABLE Livre_Auteur (
    Livre_ID INT,
    Auteur_ID INT,
    PRIMARY KEY (Livre_ID, Auteur_ID),
    FOREIGN KEY (Livre_ID) REFERENCES Livre(ID_Livre),
    FOREIGN KEY (Auteur_ID) REFERENCES Auteur(ID_auteur)
);

-- 7. Table: Membre
CREATE TABLE Membre (
    ID_mbre INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nom_mbre VARCHAR(100),
    Prenom_mbre VARCHAR(100),
    Email_mbre VARCHAR(100),
    Date_adhesion DATE
);

-- 8. Table: Emprunt
CREATE TABLE Emprunt (
    ID_emprunt INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Livre_ID INT,
    Membre_ID INT,
    Date_emprunt DATE,
    Date_retour DATE,
    FOREIGN KEY (Livre_ID) REFERENCES Livre(ID_Livre),
    FOREIGN KEY (Membre_ID) REFERENCES Membre(ID_mbre)
);
